// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import Env from "./src/config/env.ts";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: Env.DATABASE_URL,
  },
});
